// app/layout.tsx
import type { Metadata } from "next";
// import "./fonts/css/general-sans.css";
import "./chatbot.css";
import "./globals.css";

import { ToastContainer } from "react-toastify";

// const generalSans = localFont({
//   src: "./fonts/fonts/GeneralSans-Regular.woff",
//   variable: "--font-general-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Amus",
  description: "Generated by Colin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
